# playbook.yml
---
- hosts: all
  user: vagrant

  tasks:
    - copy: src=./pure-ftpd-1.0.42-1.x86_64.rpm dest=/tmp/pure-ftpd-1.0.42-1.x86_64.rpm
    - name: Install pure-ftpd package
      yum: name=/tmp/pure-ftpd-1.0.42-1.x86_64.rpm state=present
      sudo: yes

